# Spring Boot application configuration
spring.application.name=paymentsystem-service
spring.config.import=optional:dotenv:./.env

server.port=${SERVER_PORT:8085}

# MySQL datasource
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/paymentsystem_bd}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Stripe configuration
stripe.api.key=${STRIPE_API_KEY:}

# Comisión de Worklink
worklink.comision.porcentaje=${WORKLINK_COMISION_PORCENTAJE:0.10}

#Resilience4j configuration para Stripe
resilience4j.retry.instances.stripe.max-attempts=3
resilience4j.retry.instances.stripe.wait-duration=500ms
resilience4j.retry.instances.stripe.exponential-backoff-multiplier=2
resilience4j.retry.instances.stripe.retry-exceptions[0]=com.stripe.exception.ApiConnectionException
resilience4j.retry.instances.stripe.ignore-exceptions[0]=com.stripe.exception.CardException

resilience4j.circuitbreaker.instances.stripe.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.stripe.wait-duration-in-open-state=30s
