# Local Development Configuration - Overrides application.properties
spring.application.name=paymentsystem-service-local
# Database - Local Development
spring.datasource.url={ env.URL }
spring.datasource.username={ env.USERNAME }
spring.datasource.password={ env.PASSWORD }

# JPA Configuration for local development
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8085
