# Local Development Configuration - Overrides application.properties
spring.application.name=paymentsystem-service-local

# Database - Local Development
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA Configuration for local development
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:create-drop}
spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=${SERVER_PORT:8085}

# Stripe
stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
